// <auto-generated />
using System;
using Backend.Evenements.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(EvenementsContext))]
    partial class evenementsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Backend.Evenements.Entities.Evenement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Datedebut")
                        .HasColumnType("datetime")
                        .HasColumnName("datedebut");

                    b.Property<DateTime?>("Datefin")
                        .HasColumnType("datetime")
                        .HasColumnName("datefin");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("evenements", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
